/**
 * @file packages/sim-engine/src/runtime/trace/stationTraces.ts
 * @description Authentic multi-file architectural trace datasets for all stations.
 *              Models real enterprise control flow: Controller -> Service -> Repository -> Hardware.
 *              Embedded with Predict-Observe-Explain checkpoints (White & Gunstone).
 */

import type { ExecutionTraceTimeline } from "./types";

export const SMART_TV_EXECUTION_TRACE: ExecutionTraceTimeline = {
  id: "trace-smart-tv-power-flow",
  stationId: "tv",
  title: {
    ua: "Ланцюг виклику живлення: Program -> Command -> Hardware Relay",
    en: "Power Call Chain: Program -> Command -> Hardware Relay",
    da: "Strømkaldskæde: Program -> Command -> Hardware Relay",
  },
  description: {
    ua: "Покрокова трасировка передачі керування від кнопки живлення через патерн Команда до фізичного замикання реле кінескопа.",
    en: "Step-by-step trace of control transfer from power button through Command pattern down to physical CRT relay closure.",
    da: "Trin-for-trin sporing af kontrol overførsel fra tænd/sluk-knap gennem Command-mønster til fysisk CRT-relæ.",
  },
  language: "csharp",
  totalSteps: 7,
  steps: [
    {
      stepIndex: 0,
      type: "folder_enter",
      location: {
        folderId: "root",
        folderName: "VirtualTV.Solution",
        fileId: "program-cs",
        fileName: "Program.cs",
        lineStart: 12,
        lineEnd: 14,
        symbol: "Program.Main()",
        codeSnippet: "var remote = new RemoteControl(new PowerCommand(relayDriver));\nremote.PressPower();",
      },
      callStackDepth: 1,
      callStack: ["Program.Main()"],
      scopeVariables: {
        remote: "RemoteControl [Instance]",
        relayDriver: "TvRelayDriver [Ready]",
      },
      explanation: {
        ua: "Точка входу Program.Main() ініціалізує залежності та викликає remote.PressPower() на пульті дистанційного керування.",
        en: "Entrypoint Program.Main() initializes dependencies and invokes remote.PressPower() on the remote controller.",
        da: "Startpunktet Program.Main() initialiserer afhængigheder og kalder remote.PressPower() på fjernbetjeningen.",
      },
      poeQuestion: {
        id: "poe-tv-01",
        prompt: {
          ua: "Куди перейде потік виконання при виклику remote.PressPower()?",
          en: "Where will execution flow transfer upon calling remote.PressPower()?",
          da: "Hvor flytter eksekveringsstrømmen hen ved kald af remote.PressPower()?",
        },
        options: [
          {
            id: "opt-hardware",
            targetFileId: "tv-relay-driver-cs",
            targetFolderId: "folder-hardware",
            label: {
              ua: "Одразу в Hardware/TvRelayDriver.cs (напряму замкне контакт)",
              en: "Directly into Hardware/TvRelayDriver.cs (close contact directly)",
              da: "Direkte til Hardware/TvRelayDriver.cs (lukke kontakt direkte)",
            },
            isCorrect: false,
            feedback: {
              ua: "Ні. Пульт ізольований від заліза інтерфейсом ICommand, щоб не створювати жорстку зв'язність (Tight Coupling).",
              en: "Incorrect. The remote is decoupled from hardware via ICommand to prevent tight coupling.",
              da: "Forkert. Fjernbetjeningen er afkoblet fra hardware via ICommand for at undgå tæt kobling.",
            },
          },
          {
            id: "opt-command",
            targetFileId: "power-command-cs",
            targetFolderId: "folder-commands",
            label: {
              ua: "В папку Commands/ -> PowerCommand.cs (Execute)",
              en: "Into folder Commands/ -> PowerCommand.cs (Execute)",
              da: "Til mappen Commands/ -> PowerCommand.cs (Execute)",
            },
            isCorrect: true,
            feedback: {
              ua: "Точно! Патерн Command інкапсулює дію: пульт тисне Execute(), передаючи керування конкретній команді.",
              en: "Exactly! The Command pattern encapsulates the action: the remote calls Execute(), transferring control to the concrete command.",
              da: "Præcis! Command-mønsteret indkapsler handlingen: fjernbetjeningen kalder Execute().",
            },
          },
          {
            id: "opt-exit",
            targetFileId: "program-cs",
            targetFolderId: "root",
            label: {
              ua: "Програма завершиться (Return 0)",
              en: "Program will terminate (Return 0)",
              da: "Programmet afsluttes (Return 0)",
            },
            isCorrect: false,
            feedback: {
              ua: "Помилка. Виклик методу поміщає новий фрейм у стек викликів (Call Stack) і продовжує виконання.",
              en: "Incorrect. Calling a method pushes a new frame onto the Call Stack and continues execution.",
              da: "Forkert. Metodekaldet placerer en ny ramme på stakken og fortsætter.",
            },
          },
        ],
        pedagogicalRationale: {
          ua: "Формує розуміння розчеплення інтерфейсів (Dependency Inversion) та інкапсуляції запитів.",
          en: "Builds mental model of Dependency Inversion and request encapsulation.",
          da: "Opbygger en mental model for Dependency Inversion og indkapsling af anmodninger.",
        },
      },
    },
    {
      stepIndex: 1,
      type: "folder_enter",
      location: {
        folderId: "folder-commands",
        folderName: "Commands",
        fileId: "power-command-cs",
        fileName: "PowerCommand.cs",
        lineStart: 18,
        lineEnd: 24,
        symbol: "PowerCommand.Execute()",
        codeSnippet: "public void Execute() {\n    if (this._driver != null) {\n        this._driver.CloseRelayContact(25_000);\n    }\n}",
      },
      targetLocation: {
        folderId: "folder-commands",
        folderName: "Commands",
        fileId: "power-command-cs",
        fileName: "PowerCommand.cs",
        lineStart: 18,
        lineEnd: 24,
        symbol: "PowerCommand.Execute()",
      },
      callStackDepth: 2,
      callStack: ["Program.Main()", "PowerCommand.Execute()"],
      scopeVariables: {
        this: "PowerCommand",
        "_driver": "TvRelayDriver [Active]",
        "anodeVoltage": 25000,
      },
      explanation: {
        ua: "Керування перейшло в Commands/PowerCommand.cs. Метод Execute() перевіряє наявність драйвера реле і викликає CloseRelayContact(25000).",
        en: "Control transferred into Commands/PowerCommand.cs. Execute() checks relay driver presence and calls CloseRelayContact(25000).",
        da: "Styringen overgik til Commands/PowerCommand.cs. Execute() kalder CloseRelayContact(25000).",
      },
    },
    {
      stepIndex: 2,
      type: "branch_eval",
      location: {
        folderId: "folder-commands",
        folderName: "Commands",
        fileId: "power-command-cs",
        fileName: "PowerCommand.cs",
        lineStart: 19,
        lineEnd: 19,
        symbol: "if (_driver != null)",
        codeSnippet: "if (this._driver != null) // Evaluated to TRUE",
      },
      callStackDepth: 2,
      callStack: ["Program.Main()", "PowerCommand.Execute()"],
      scopeVariables: {
        "_driver != null": true,
      },
      explanation: {
        ua: "Умова if (_driver != null) успішно обчислена як TRUE. Запобіжник NullReferenceException спрацював штатно.",
        en: "Condition if (_driver != null) evaluated to TRUE. NullReferenceException guard passed.",
        da: "Betingelsen if (_driver != null) evalueredes til TRUE.",
      },
    },
    {
      stepIndex: 3,
      type: "function_call",
      location: {
        folderId: "folder-hardware",
        folderName: "Hardware",
        fileId: "tv-relay-driver-cs",
        fileName: "TvRelayDriver.cs",
        lineStart: 32,
        lineEnd: 41,
        symbol: "TvRelayDriver.CloseRelayContact()",
        codeSnippet: "public bool CloseRelayContact(int targetAnodeVoltage) {\n    this.IsCoilEnergized = true;\n    this.ActualVoltage = targetAnodeVoltage;\n    return true;\n}",
      },
      targetLocation: {
        folderId: "folder-hardware",
        folderName: "Hardware",
        fileId: "tv-relay-driver-cs",
        fileName: "TvRelayDriver.cs",
        lineStart: 32,
        lineEnd: 41,
        symbol: "TvRelayDriver.CloseRelayContact()",
      },
      callStackDepth: 3,
      callStack: ["Program.Main()", "PowerCommand.Execute()", "TvRelayDriver.CloseRelayContact()"],
      scopeVariables: {
        targetAnodeVoltage: 25000,
        IsCoilEnergized: true,
        ActualVoltage: 25000,
      },
      explanation: {
        ua: "Потік увійшов у шар драйверів апаратного забезпечення Hardware/TvRelayDriver.cs. Котушка реле замикає контакт 25 кВ.",
        en: "Thread entered the hardware driver layer Hardware/TvRelayDriver.cs. Relay coil energizes CRT 25kV contact.",
        da: "Tråden gik ind i hardware-driverlaget Hardware/TvRelayDriver.cs. Relæspolen lukker 25kV-kontakten.",
      },
    },
    {
      stepIndex: 4,
      type: "return_unwind",
      location: {
        folderId: "folder-hardware",
        folderName: "Hardware",
        fileId: "tv-relay-driver-cs",
        fileName: "TvRelayDriver.cs",
        lineStart: 35,
        lineEnd: 35,
        symbol: "return true;",
        codeSnippet: "return true; // [TERMINATION POINT] Stack Frame Pop",
      },
      targetLocation: {
        folderId: "folder-commands",
        folderName: "Commands",
        fileId: "power-command-cs",
        fileName: "PowerCommand.cs",
        lineStart: 21,
        lineEnd: 21,
        symbol: "PowerCommand.Execute()",
      },
      callStackDepth: 3,
      callStack: ["Program.Main()", "PowerCommand.Execute()", "TvRelayDriver.CloseRelayContact()"],
      returnValue: {
        type: "bool",
        value: "true",
        summary: {
          ua: "Контакт успішно замкнено (true)",
          en: "Contact successfully closed (true)",
          da: "Kontakt lukket med succes (true)",
        },
        terminationReason: {
          ua: "Метод завершився за явним оператором return true. Стек викликів скидає верхній фрейм і повертає керування у PowerCommand.cs.",
          en: "Method concluded via explicit return true. Call stack pops top frame and unwinds back to PowerCommand.cs.",
          da: "Metoden afsluttedes via explicit return true. Stakken fjerner øverste ramme og returnerer til PowerCommand.cs.",
        },
      },
      explanation: {
        ua: "Драйвер закінчив виконання і повертає значення true. Фрейм виштовхується зі стеку (Stack Unwinding).",
        en: "Driver finished execution and returns true. Frame is popped from stack (Stack Unwinding).",
        da: "Driveren afsluttede eksekvering og returnerer true.",
      },
    },
    {
      stepIndex: 5,
      type: "return_unwind",
      location: {
        folderId: "folder-commands",
        folderName: "Commands",
        fileId: "power-command-cs",
        fileName: "PowerCommand.cs",
        lineStart: 24,
        lineEnd: 24,
        symbol: "PowerCommand.Execute() [End]",
        codeSnippet: "} // End of Execute method, returns void to caller",
      },
      targetLocation: {
        folderId: "root",
        folderName: "VirtualTV.Solution",
        fileId: "program-cs",
        fileName: "Program.cs",
        lineStart: 15,
        lineEnd: 15,
        symbol: "Program.Main()",
      },
      callStackDepth: 2,
      callStack: ["Program.Main()", "PowerCommand.Execute()"],
      returnValue: {
        type: "void",
        value: "void",
        summary: {
          ua: "Команда виконана без помилок",
          en: "Command executed cleanly",
          da: "Kommando udført uden fejl",
        },
        terminationReason: {
          ua: "Досягнуто кінця тіла методу (фігурна дужка }). Керування повертається в точку виклику Program.cs:15.",
          en: "Reached end of method body (closing brace }). Control returns to invocation site Program.cs:15.",
          da: "Nåede slutningen af metoden. Kontrol returnerer til Program.cs:15.",
        },
      },
      explanation: {
        ua: "Команда PowerCommand завершилась. Керування повернулося до вихідної точки в Program.Main().",
        en: "PowerCommand finished. Control returned to calling origin in Program.Main().",
        da: "PowerCommand afsluttedes. Styringen vendte tilbage til Program.Main().",
      },
    },
    {
      stepIndex: 6,
      type: "file_focus",
      location: {
        folderId: "root",
        folderName: "VirtualTV.Solution",
        fileId: "program-cs",
        fileName: "Program.cs",
        lineStart: 15,
        lineEnd: 17,
        symbol: "Program.Main() [Done]",
        codeSnippet: "Console.WriteLine(\"[TV READY] Raster illuminated 25kV\");",
      },
      callStackDepth: 1,
      callStack: ["Program.Main()"],
      scopeVariables: {
        tvState: "{ IsOn: true, AnodeKv: 25 }",
      },
      explanation: {
        ua: "Цикл виконання завершено! Телевізор перейшов у робочий стан (IsOn = true). Ментальна модель замкнулася: Program -> Command -> Driver -> Return.",
        en: "Execution cycle complete! TV entered energized state (IsOn = true). Mental model closed: Program -> Command -> Driver -> Return.",
        da: "Eksekveringscyklus fuldført! TV tændt.",
      },
    },
  ],
};

export const API_FORGE_EXECUTION_TRACE: ExecutionTraceTimeline = {
  id: "trace-api-forge-order-pipeline",
  stationId: "api",
  title: {
    ua: "HTTP Запит: Controller -> OrderService -> Repository -> 201 Created",
    en: "HTTP Request: Controller -> OrderService -> Repository -> 201 Created",
    da: "HTTP Anmodning: Controller -> OrderService -> Repository -> 201 Created",
  },
  description: {
    ua: "Трасировка проходження REST POST /api/orders через конвеєр ASP.NET Core / Go net/http з валідацією інваріантів та збереженням у репозиторій.",
    en: "Trace of REST POST /api/orders traversing ASP.NET Core / Go net/http pipeline with business invariant validation and repository persistence.",
    da: "Sporing af REST POST /api/orders gennem ASP.NET Core / Go pipeline.",
  },
  language: "csharp",
  totalSteps: 7,
  steps: [
    {
      stepIndex: 0,
      type: "folder_enter",
      location: {
        folderId: "folder-controllers",
        folderName: "Controllers",
        fileId: "orders-controller-cs",
        fileName: "OrdersController.cs",
        lineStart: 25,
        lineEnd: 28,
        symbol: "OrdersController.CreateOrder([FromBody] OrderDto dto)",
        codeSnippet: "[HttpPost]\npublic async Task<IResult> CreateOrder([FromBody] OrderDto dto) {\n    var result = await _orderService.PlaceOrderAsync(dto);\n    return Results.Created($\"/api/orders/{result.Id}\", result);\n}",
      },
      callStackDepth: 1,
      callStack: ["OrdersController.CreateOrder()"],
      scopeVariables: {
        "dto.ItemId": "item-994",
        "dto.Amount": 450,
      },
      explanation: {
        ua: "Kestrel обробив заголовки запиту, десеріалізував JSON-боді в об'єкт dto і викликав контролер.",
        en: "Kestrel parsed HTTP headers, deserialized JSON body into dto and invoked controller action.",
        da: "Kestrel behandlede anmodning og kaldte controller.",
      },
      poeQuestion: {
        id: "poe-api-01",
        prompt: {
          ua: "Де повинна перевірятися бізнес-валідація (чи достатньо товару на складі)?",
          en: "Where should business domain validation (stock availability) be checked?",
          da: "Hvor skal domænevalidering tjekkes?",
        },
        options: [
          {
            id: "opt-repo",
            targetFileId: "order-repository-cs",
            targetFolderId: "folder-repositories",
            label: {
              ua: "В OrderRepository.cs напряму через SQL-запит",
              en: "In OrderRepository.cs directly via raw SQL query",
              da: "I OrderRepository.cs direkte",
            },
            isCorrect: false,
            feedback: {
              ua: "Помилка. Репозиторій відповідає лише за читання/запис (Persistence), а не за правила бізнесу.",
              en: "Incorrect. Repositories handle persistence, not domain business rules.",
              da: "Forkert. Repository er kun til persistence.",
            },
          },
          {
            id: "opt-service",
            targetFileId: "order-service-cs",
            targetFolderId: "folder-services",
            label: {
              ua: "В Services/OrderService.cs (доменний сервіс)",
              en: "In Services/OrderService.cs (domain service layer)",
              da: "I Services/OrderService.cs (domænelag)",
            },
            isCorrect: true,
            feedback: {
              ua: "Правильно! Чиста архітектура відокремлює доменні правила (Сервіс) від деталей збереження (Репозиторій).",
              en: "Correct! Clean architecture isolates business rules (Service) from persistence details (Repository).",
              da: "Korrekt! Ren arkitektur isolerer forretningsregler.",
            },
          },
        ],
        pedagogicalRationale: {
          ua: "Вчить розділенню відповідальності (Single Responsibility Principle) у бекенд-розробці.",
          en: "Teaches Single Responsibility Principle in backend architecture.",
          da: "Lærer princippet om enkelt ansvar.",
        },
      },
    },
    {
      stepIndex: 1,
      type: "function_call",
      location: {
        folderId: "folder-services",
        folderName: "Services",
        fileId: "order-service-cs",
        fileName: "OrderService.cs",
        lineStart: 40,
        lineEnd: 48,
        symbol: "OrderService.PlaceOrderAsync()",
        codeSnippet: "public async Task<OrderResult> PlaceOrderAsync(OrderDto dto) {\n    if (dto.Amount <= 0) throw new ArgumentException(\"Invalid amount\");\n    var order = new Order(Guid.NewGuid(), dto.ItemId, dto.Amount);\n    await _repo.SaveAsync(order);\n    return new OrderResult(order.Id, \"Confirmed\");\n}",
      },
      targetLocation: {
        folderId: "folder-services",
        folderName: "Services",
        fileId: "order-service-cs",
        fileName: "OrderService.cs",
        lineStart: 40,
        lineEnd: 48,
        symbol: "OrderService.PlaceOrderAsync()",
      },
      callStackDepth: 2,
      callStack: ["OrdersController.CreateOrder()", "OrderService.PlaceOrderAsync()"],
      scopeVariables: {
        "dto.Amount": 450,
        "validationPassed": true,
      },
      explanation: {
        ua: "Сервіс перевірив інваріант dto.Amount > 0. Створюється нова сутність Order з унікальним Guid.",
        en: "Service validated invariant dto.Amount > 0. New Order entity created with unique Guid.",
        da: "Servicen validerede invarianten.",
      },
    },
    {
      stepIndex: 2,
      type: "function_call",
      location: {
        folderId: "folder-repositories",
        folderName: "Repositories",
        fileId: "order-repository-cs",
        fileName: "OrderRepository.cs",
        lineStart: 18,
        lineEnd: 24,
        symbol: "OrderRepository.SaveAsync()",
        codeSnippet: "public async Task SaveAsync(Order order) {\n    this._inMemoryDb[order.Id] = order;\n    await Task.Yield();\n}",
      },
      targetLocation: {
        folderId: "folder-repositories",
        folderName: "Repositories",
        fileId: "order-repository-cs",
        fileName: "OrderRepository.cs",
        lineStart: 18,
        lineEnd: 24,
        symbol: "OrderRepository.SaveAsync()",
      },
      callStackDepth: 3,
      callStack: ["OrdersController.CreateOrder()", "OrderService.PlaceOrderAsync()", "OrderRepository.SaveAsync()"],
      scopeVariables: {
        "order.Id": "8f3b-4192",
        "savedToDb": true,
      },
      explanation: {
        ua: "Репозиторій зафіксував замовлення у базі даних (у сховищі пам'яті).",
        en: "Repository committed the order to memory storage / DB.",
        da: "Repository gemte ordren.",
      },
    },
    {
      stepIndex: 3,
      type: "return_unwind",
      location: {
        folderId: "folder-repositories",
        folderName: "Repositories",
        fileId: "order-repository-cs",
        fileName: "OrderRepository.cs",
        lineStart: 23,
        lineEnd: 23,
        symbol: "Task.CompletedTask",
        codeSnippet: "return Task.CompletedTask;",
      },
      targetLocation: {
        folderId: "folder-services",
        folderName: "Services",
        fileId: "order-service-cs",
        fileName: "OrderService.cs",
        lineStart: 44,
        lineEnd: 44,
        symbol: "OrderService.PlaceOrderAsync()",
      },
      callStackDepth: 3,
      callStack: ["OrdersController.CreateOrder()", "OrderService.PlaceOrderAsync()", "OrderRepository.SaveAsync()"],
      returnValue: {
        type: "Task",
        value: "TaskCompleted",
        summary: {
          ua: "Запис успішно збережено в базі",
          en: "Record successfully persisted to DB",
          da: "Post gemt i databasen",
        },
        terminationReason: {
          ua: "Асинхронний таск завершився без помилок. Керування повертається у сервіс через await.",
          en: "Async Task completed with 0 faults. Execution resumes in service after await.",
          da: "Async opgave fuldført.",
        },
      },
      explanation: {
        ua: "Асинхронна операція запису завершилась, фрейм репозиторію скидається.",
        en: "Async write operation concluded, repository frame is popped.",
        da: "Async skrivning afsluttet.",
      },
    },
    {
      stepIndex: 4,
      type: "return_unwind",
      location: {
        folderId: "folder-services",
        folderName: "Services",
        fileId: "order-service-cs",
        fileName: "OrderService.cs",
        lineStart: 45,
        lineEnd: 45,
        symbol: "return OrderResult",
        codeSnippet: "return new OrderResult(order.Id, \"Confirmed\");",
      },
      targetLocation: {
        folderId: "folder-controllers",
        folderName: "Controllers",
        fileId: "orders-controller-cs",
        fileName: "OrdersController.cs",
        lineStart: 27,
        lineEnd: 27,
        symbol: "OrdersController.CreateOrder()",
      },
      callStackDepth: 2,
      callStack: ["OrdersController.CreateOrder()", "OrderService.PlaceOrderAsync()"],
      returnValue: {
        type: "OrderResult",
        value: "{ Id: '8f3b-4192', Status: 'Confirmed' }",
        summary: {
          ua: "Замовлення підтверджено сервісом",
          en: "Order confirmed by service",
          da: "Ordre bekræftet",
        },
        terminationReason: {
          ua: "Сервіс завершив бізнес-транзакцію і повернув об'єкт-результат контролеру.",
          en: "Service closed business transaction and returned domain result to controller.",
          da: "Service returnerede resultat til controller.",
        },
      },
      explanation: {
        ua: "Сервіс повертає результат контролеру.",
        en: "Service returns result to controller.",
        da: "Service returnerer til controller.",
      },
    },
    {
      stepIndex: 5,
      type: "return_unwind",
      location: {
        folderId: "folder-controllers",
        folderName: "Controllers",
        fileId: "orders-controller-cs",
        fileName: "OrdersController.cs",
        lineStart: 28,
        lineEnd: 28,
        symbol: "return Results.Created()",
        codeSnippet: "return Results.Created($\"/api/orders/{result.Id}\", result);",
      },
      callStackDepth: 1,
      callStack: ["OrdersController.CreateOrder()"],
      returnValue: {
        type: "IResult (HTTP 201)",
        value: "201 Created",
        summary: {
          ua: "HTTP 201 Created з Location header",
          en: "HTTP 201 Created with Location header",
          da: "HTTP 201 Created",
        },
        terminationReason: {
          ua: "Контролер формує фінальну відповідь HTTP 201 Created з посиланням на створений ресурс.",
          en: "Controller crafts final HTTP 201 Created response with resource URI.",
          da: "Controller danner HTTP 201 Created svar.",
        },
      },
      explanation: {
        ua: "Контролер сформував HTTP-відповідь 201 Created. Клієнт отримує JSON.",
        en: "Controller assembled HTTP 201 Created response. Client receives JSON payload.",
        da: "Controller samlede HTTP 201 svar.",
      },
    },
    {
      stepIndex: 6,
      type: "file_focus",
      location: {
        folderId: "client",
        folderName: "Client",
        fileId: "curl-request",
        fileName: "HTTP Response",
        lineStart: 1,
        lineEnd: 4,
        symbol: "HTTP/1.1 201 Created",
        codeSnippet: "HTTP/1.1 201 Created\nLocation: /api/orders/8f3b-4192\nContent-Type: application/json\n{\"id\":\"8f3b-4192\",\"status\":\"Confirmed\"}",
      },
      callStackDepth: 0,
      callStack: [],
      explanation: {
        ua: "Повний HTTP-цикл завершено! Замовлення зареєстровано через усі рівні архітектури.",
        en: "Full HTTP lifecycle completed! Order registered across all architectural tiers.",
        da: "Fuld HTTP cyklus fuldført!",
      },
    },
  ],
};

export const POS_EXECUTION_TRACE: ExecutionTraceTimeline = {
  id: "trace-pos-transaction-flow",
  stationId: "pos",
  title: {
    ua: "Фінансова транзакція: Terminal -> Ledger -> NFC Reader",
    en: "Financial Transaction: Terminal -> Ledger -> NFC Reader",
    da: "Finansiel Transaktion: Terminal -> Ledger -> NFC Reader",
  },
  description: {
    ua: "Трасировка обробки банківської транзакції з перевіркою інваріантів балансу та генерацією криптографічного чека.",
    en: "Trace of financial transaction processing with balance invariant validation and cryptographic receipt generation.",
    da: "Sporing af finansiel transaktionsbehandling.",
  },
  language: "csharp",
  totalSteps: 5,
  steps: [
    {
      stepIndex: 0,
      type: "folder_enter",
      location: {
        folderId: "root",
        folderName: "PosTerminal.Solution",
        fileId: "program-cs",
        fileName: "Program.cs",
        lineStart: 15,
        lineEnd: 18,
        symbol: "CashierSession.ProcessPayment(500)",
        codeSnippet: "var ledger = new AccountLedger(balance: 1200);\nvar terminal = new PosTerminal(ledger);\nterminal.AuthorizeCard(500);",
      },
      callStackDepth: 1,
      callStack: ["CashierSession.ProcessPayment()"],
      scopeVariables: {
        requestedAmount: 500,
        initialBalance: 1200,
      },
      explanation: {
        ua: "Касова сесія ініціює списання 500 грн за покупку.",
        en: "Cashier session initiates payment of 500 UAH.",
        da: "Kassesession starter betaling.",
      },
      poeQuestion: {
        id: "poe-pos-01",
        prompt: {
          ua: "Який компонент зобов'язаний перевірити умову достатнього балансу (Amount <= Balance)?",
          en: "Which component must validate sufficient balance invariant (Amount <= Balance)?",
          da: "Hvilken komponent skal validere tilstrækkelig saldo?",
        },
        options: [
          {
            id: "opt-nfc",
            targetFileId: "nfc-reader-cs",
            targetFolderId: "folder-hardware",
            label: {
              ua: "NFC Reader (зчитувач картки)",
              en: "NFC Reader (hardware card sensor)",
              da: "NFC Reader",
            },
            isCorrect: false,
            feedback: {
              ua: "Помилка. Зчитувач карток лише отримує токен і не має доступу до балансу рахунку клієнта.",
              en: "Incorrect. NFC Reader only reads EMV tokens; it has no account balance access.",
              da: "Forkert. NFC Reader læser kun tokens.",
            },
          },
          {
            id: "opt-ledger",
            targetFileId: "account-ledger-cs",
            targetFolderId: "folder-services",
            label: {
              ua: "Services/AccountLedger.cs (Бухгалтерська книга)",
              en: "Services/AccountLedger.cs (Account Ledger Invariants)",
              da: "Services/AccountLedger.cs",
            },
            isCorrect: true,
            feedback: {
              ua: "Правильно! Фінансовий інваріант захищає банк від овердрафту саме в шарі фінансової книги.",
              en: "Correct! Ledger maintains financial account invariants against illegal overdraft.",
              da: "Korrekt! Hovedbog sikrer finansielle invarianter.",
            },
          },
        ],
        pedagogicalRationale: {
          ua: "Вчить захисту бізнес-інваріантів у транзакційних системах.",
          en: "Teaches transactional business invariant enforcement.",
          da: "Lærer håndhævelse af forretningsinvarianter.",
        },
      },
    },
    {
      stepIndex: 1,
      type: "function_call",
      location: {
        folderId: "folder-services",
        folderName: "Services",
        fileId: "account-ledger-cs",
        fileName: "AccountLedger.cs",
        lineStart: 22,
        lineEnd: 27,
        symbol: "AccountLedger.Debit(500)",
        codeSnippet: "public bool Debit(decimal amount) {\n    if (amount > this.Balance) return false;\n    this.Balance -= amount;\n    return true;\n}",
      },
      targetLocation: {
        folderId: "folder-services",
        folderName: "Services",
        fileId: "account-ledger-cs",
        fileName: "AccountLedger.cs",
        lineStart: 22,
        lineEnd: 27,
        symbol: "AccountLedger.Debit(500)",
      },
      callStackDepth: 2,
      callStack: ["CashierSession.ProcessPayment()", "AccountLedger.Debit()"],
      scopeVariables: {
        "amount <= Balance": true,
        remainingBalance: 700,
      },
      explanation: {
        ua: "Ledger перевірив баланс (1200 >= 500) і успішно зменшив залишок до 700 грн.",
        en: "Ledger validated funds (1200 >= 500) and deducted balance to 700 UAH.",
        da: "Ledger validerede saldo.",
      },
    },
    {
      stepIndex: 2,
      type: "function_call",
      location: {
        folderId: "folder-hardware",
        folderName: "Hardware",
        fileId: "nfc-reader-cs",
        fileName: "NfcReader.cs",
        lineStart: 14,
        lineEnd: 18,
        symbol: "NfcReader.GenerateAuthCryptogram()",
        codeSnippet: "public string GenerateAuthCryptogram() => \"ARQC-9182-APPROVED\";",
      },
      targetLocation: {
        folderId: "folder-hardware",
        folderName: "Hardware",
        fileId: "nfc-reader-cs",
        fileName: "NfcReader.cs",
        lineStart: 14,
        lineEnd: 18,
        symbol: "NfcReader.GenerateAuthCryptogram()",
      },
      callStackDepth: 3,
      callStack: ["CashierSession.ProcessPayment()", "AccountLedger.Debit()", "NfcReader.GenerateAuthCryptogram()"],
      scopeVariables: {
        cryptogram: "ARQC-9182-APPROVED",
      },
      explanation: {
        ua: "Чіп карти згенерував криптографічний токен схвалення транзакції.",
        en: "Smart chip generated EMV authorization cryptogram.",
        da: "Chip genererede godkendelseskryptogram.",
      },
    },
    {
      stepIndex: 3,
      type: "return_unwind",
      location: {
        folderId: "folder-hardware",
        folderName: "Hardware",
        fileId: "nfc-reader-cs",
        fileName: "NfcReader.cs",
        lineStart: 17,
        lineEnd: 17,
        symbol: "return Cryptogram",
        codeSnippet: "return \"ARQC-9182-APPROVED\";",
      },
      targetLocation: {
        folderId: "folder-services",
        folderName: "Services",
        fileId: "account-ledger-cs",
        fileName: "AccountLedger.cs",
        lineStart: 26,
        lineEnd: 26,
        symbol: "AccountLedger.Debit()",
      },
      callStackDepth: 3,
      callStack: ["CashierSession.ProcessPayment()", "AccountLedger.Debit()", "NfcReader.GenerateAuthCryptogram()"],
      returnValue: {
        type: "string",
        value: "\"ARQC-9182-APPROVED\"",
        summary: {
          ua: "Криптограму отримано",
          en: "Cryptogram obtained",
          da: "Kryptogram modtaget",
        },
        terminationReason: {
          ua: "Апаратний чіп підтвердив транзакцію та повернув код підтвердження.",
          en: "Hardware sensor confirmed transaction and popped stack frame.",
          da: "Hardware sensor bekræftede transaktion.",
        },
      },
      explanation: {
        ua: "Стек розгортається назад у вихідний метод.",
        en: "Stack unwinds back to caller.",
        da: "Stakken rulles tilbage.",
      },
    },
    {
      stepIndex: 4,
      type: "file_focus",
      location: {
        folderId: "root",
        folderName: "PosTerminal.Solution",
        fileId: "program-cs",
        fileName: "Program.cs",
        lineStart: 18,
        lineEnd: 20,
        symbol: "CashierSession [Complete]",
        codeSnippet: "Console.WriteLine(\"[PAYMENT SUCCESS] Receipt: AUTH-8921\");",
      },
      callStackDepth: 1,
      callStack: ["CashierSession.ProcessPayment()"],
      explanation: {
        ua: "Транзакція завершена успішно. Чек надруковано, кошти списано.",
        en: "Transaction complete. Receipt printed, balance charged.",
        da: "Transaktion fuldført.",
      },
    },
  ],
};

export const GIT_EXECUTION_TRACE: ExecutionTraceTimeline = {
  id: "trace-git-dag-commit",
  stationId: "git",
  title: {
    ua: "Git Commit: CLI -> Object Store -> Ref Update",
    en: "Git Commit: CLI -> Object Store -> Ref Update",
    da: "Git Commit: CLI -> Object Store -> Ref Update",
  },
  description: {
    ua: "Трасировка внутрішнього устрою git commit: створення незмінного блобу, хешування дерева та оновлення вказівника гілки.",
    en: "Trace of internal git commit mechanics: immutable blob creation, tree hashing, and branch ref update.",
    da: "Sporing af interne git commit mekanikker.",
  },
  language: "go",
  totalSteps: 5,
  steps: [
    {
      stepIndex: 0,
      type: "folder_enter",
      location: {
        folderId: "folder-cmd",
        folderName: "cmd",
        fileId: "git-main-go",
        fileName: "main.go",
        lineStart: 10,
        lineEnd: 15,
        symbol: "main() -> git.Commit()",
        codeSnippet: "func main() {\n    repo := git.OpenRepository(\".git\")\n    commitSha := repo.Commit(\"Initial commit\")\n    fmt.Printf(\"[main %s] %s\\n\", commitSha[:7], \"Initial commit\")\n}",
      },
      callStackDepth: 1,
      callStack: ["main()"],
      scopeVariables: {
        "commitMessage": "\"Initial commit\"",
      },
      explanation: {
        ua: "CLI-команда git commit починає формувати новий вузол графа DAG.",
        en: "CLI git commit starts building a new DAG node.",
        da: "CLI git commit begynder opbygning.",
      },
      poeQuestion: {
        id: "poe-git-01",
        prompt: {
          ua: "Де зберігаються незмінні байти файлів у внутрішній структурі Git?",
          en: "Where are immutable file bytes stored inside Git internal structure?",
          da: "Hvor gemmes uforanderlige bytes i Git?",
        },
        options: [
          {
            id: "opt-object-store",
            targetFileId: "git-object-store-go",
            targetFolderId: "folder-storage",
            label: {
              ua: "В Object Store (.git/objects) у вигляді хешованих блобів",
              en: "In Object Store (.git/objects) as content-addressed blobs",
              da: "I Object Store (.git/objects)",
            },
            isCorrect: true,
            feedback: {
              ua: "Блискуче! Git є адресованим за вмістом сховищем (Content-Addressed Store): ключ — це SHA-хеш, значення — байти.",
              en: "Brilliant! Git is a content-addressed object store: SHA-1 hash is the key, payload is the value.",
              da: "Korrekt! Git er et indholdsadresseret objektlager.",
            },
          },
          {
            id: "opt-branch-ref",
            targetFileId: "git-ref-go",
            targetFolderId: "folder-refs",
            label: {
              ua: "У файлі гілки .git/refs/heads/main",
              en: "Inside branch ref file .git/refs/heads/main",
              da: "I .git/refs/heads/main",
            },
            isCorrect: false,
            feedback: {
              ua: "Ні. Файл гілки містить лише 40-символьний рядок хешу коміту, а не самі файли.",
              en: "Incorrect. Branch files only store 40-character commit hashes, not file data.",
              da: "Forkert. Grenfiler gemmer kun hashes.",
            },
          },
        ],
        pedagogicalRationale: {
          ua: "Формує розуміння DAG (Directed Acyclic Graph) та content-addressable storage.",
          en: "Builds mental model of DAG and content-addressable storage.",
          da: "Opbygger mental model for DAG.",
        },
      },
    },
    {
      stepIndex: 1,
      type: "function_call",
      location: {
        folderId: "folder-storage",
        folderName: "storage",
        fileId: "git-object-store-go",
        fileName: "object_store.go",
        lineStart: 25,
        lineEnd: 32,
        symbol: "ObjectStore.WriteBlob()",
        codeSnippet: "func (s *ObjectStore) WriteBlob(data []byte) string {\n    hash := sha1.Sum(data)\n    hexSha := hex.EncodeToString(hash[:])\n    s.persistToDisk(hexSha, data)\n    return hexSha\n}",
      },
      targetLocation: {
        folderId: "folder-storage",
        folderName: "storage",
        fileId: "git-object-store-go",
        fileName: "object_store.go",
        lineStart: 25,
        lineEnd: 32,
        symbol: "ObjectStore.WriteBlob()",
      },
      callStackDepth: 2,
      callStack: ["main()", "ObjectStore.WriteBlob()"],
      scopeVariables: {
        "blobSha": "e69de29bb2d1d6434b8b29ae775ad8c2e48c5391",
      },
      explanation: {
        ua: "Git обчислює SHA-1 від даних та зберігає стиснутий zlib-блоб у .git/objects/e6/9d...",
        en: "Git calculates SHA-1 of file bytes and writes zlib compressed blob into .git/objects.",
        da: "Git beregner SHA-1 og gemmer blob.",
      },
    },
    {
      stepIndex: 2,
      type: "function_call",
      location: {
        folderId: "folder-refs",
        folderName: "refs",
        fileId: "git-ref-go",
        fileName: "ref.go",
        lineStart: 18,
        lineEnd: 24,
        symbol: "RefStore.UpdateHead()",
        codeSnippet: "func (r *RefStore) UpdateHead(newCommitSha string) error {\n    return os.WriteFile(\".git/refs/heads/main\", []byte(newCommitSha), 0644)\n}",
      },
      targetLocation: {
        folderId: "folder-refs",
        folderName: "refs",
        fileId: "git-ref-go",
        fileName: "ref.go",
        lineStart: 18,
        lineEnd: 24,
        symbol: "RefStore.UpdateHead()",
      },
      callStackDepth: 3,
      callStack: ["main()", "ObjectStore.WriteBlob()", "RefStore.UpdateHead()"],
      scopeVariables: {
        "targetRef": "refs/heads/main",
        "newSha": "4f8b1a9c3d",
      },
      explanation: {
        ua: "Вказівник гілки 'main' пересунуто на новий щойно створений коміт.",
        en: "Branch pointer 'main' moved forward to new commit hash.",
        da: "Grenpeger flyttet.",
      },
    },
    {
      stepIndex: 3,
      type: "return_unwind",
      location: {
        folderId: "folder-refs",
        folderName: "refs",
        fileId: "git-ref-go",
        fileName: "ref.go",
        lineStart: 23,
        lineEnd: 23,
        symbol: "return nil",
        codeSnippet: "return nil // Reference successfully updated",
      },
      targetLocation: {
        folderId: "folder-cmd",
        folderName: "cmd",
        fileId: "git-main-go",
        fileName: "main.go",
        lineStart: 13,
        lineEnd: 13,
        symbol: "main()",
      },
      callStackDepth: 2,
      callStack: ["main()", "ObjectStore.WriteBlob()"],
      returnValue: {
        type: "error",
        value: "nil",
        summary: {
          ua: "Гілку успішно оновлено",
          en: "Branch pointer updated",
          da: "Gren opdateret",
        },
        terminationReason: {
          ua: "Файл .git/refs/heads/main перезаписано. Стек повертається у функцію main.",
          en: "Reference file written cleanly, stack frame unwound to main().",
          da: "Referencefil skrevet.",
        },
      },
      explanation: {
        ua: "Оновлення посилання завершено без помилок.",
        en: "Reference update concluded cleanly.",
        da: "Opdatering afsluttet.",
      },
    },
    {
      stepIndex: 4,
      type: "file_focus",
      location: {
        folderId: "folder-cmd",
        folderName: "cmd",
        fileId: "git-main-go",
        fileName: "main.go",
        lineStart: 13,
        lineEnd: 15,
        symbol: "main() [Committed]",
        codeSnippet: "fmt.Println(\"[main 4f8b1a9] Initial commit\")",
      },
      callStackDepth: 1,
      callStack: ["main()"],
      explanation: {
        ua: "Коміт зафіксовано в графі! Студент бачить, як змінився HEAD.",
        en: "Commit anchored in DAG! Student sees HEAD advance.",
        da: "Commit forankret.",
      },
    },
  ],
};

export const BANDIT_EXECUTION_TRACE: ExecutionTraceTimeline = {
  id: "trace-bandit-security-firewall",
  stationId: "bandit",
  title: {
    ua: "Кіберзахист: Ingress Packet -> Security Middleware -> Sanitizer",
    en: "Cyber Defense: Ingress Packet -> Security Middleware -> Sanitizer",
    da: "Cybersikkerhed: Ingress Packet -> Security Middleware -> Sanitizer",
  },
  description: {
    ua: "Трасировка інспекції мережевого пакету: виявлення SQL Injection та інваріантна нейтралізація загрози.",
    en: "Trace of network packet inspection: SQL Injection heuristic detection and invariant threat mitigation.",
    da: "Sporing af netværkspakkeinspektion.",
  },
  language: "csharp",
  totalSteps: 5,
  steps: [
    {
      stepIndex: 0,
      type: "folder_enter",
      location: {
        folderId: "root",
        folderName: "CyberBandit.Solution",
        fileId: "program-cs",
        fileName: "Program.cs",
        lineStart: 12,
        lineEnd: 15,
        symbol: "NetworkListener.OnPacketReceived(rawBytes)",
        codeSnippet: "var filter = new SecurityFilter();\nvar inspector = new PacketInspector(filter);\ninspector.ProcessPacket(\"SELECT * FROM users WHERE id = '1' OR '1'='1'\");",
      },
      callStackDepth: 1,
      callStack: ["NetworkListener.OnPacketReceived()"],
      scopeVariables: {
        payload: "'1' OR '1'='1'",
        protocol: "TCP/8080",
      },
      explanation: {
        ua: "Сокет отримав підозрілий HTTP-запит із вхідним корисним навантаженням.",
        en: "Socket received suspicious ingress packet payload.",
        da: "Socket modtog pakke.",
      },
      poeQuestion: {
        id: "poe-bandit-01",
        prompt: {
          ua: "Де повинен спрацювати захист від SQL Injection, щоб атака не дісталася до бази даних?",
          en: "Where must SQL Injection guard activate before reaching database?",
          da: "Hvor skal SQL Injection beskyttelse aktiveres?",
        },
        options: [
          {
            id: "opt-middleware",
            targetFileId: "security-filter-cs",
            targetFolderId: "folder-middleware",
            label: {
              ua: "В Middleware/SecurityFilter.cs до виконання запиту",
              en: "In Middleware/SecurityFilter.cs before query execution",
              da: "I Middleware/SecurityFilter.cs",
            },
            isCorrect: true,
            feedback: {
              ua: "Правильно! Захисний периметр фільтрує небезпечні символи на рівні конвеєра доступу.",
              en: "Correct! Perimeter filter sanitizes injection strings before reaching database adapter.",
              da: "Korrekt! Filter renser før databasen.",
            },
          },
          {
            id: "opt-db",
            targetFileId: "program-cs",
            targetFolderId: "root",
            label: {
              ua: "У самій базі даних після виконання запиту",
              en: "Inside the database after query runs",
              da: "I selve databasen",
            },
            isCorrect: false,
            feedback: {
              ua: "Катастрофічна помилка! Якщо шкідливий SQL потрапить у СУБД, дані будуть скомпрометовані.",
              en: "Catastrophic! If malicious SQL reaches DB engine, data is already leaked.",
              da: "Katastrofal fejl!",
            },
          },
        ],
        pedagogicalRationale: {
          ua: "Вчить принципу захисту в глибину (Defense in Depth) та ранній санітизації входів.",
          en: "Teaches Defense in Depth and early input sanitization.",
          da: "Lærer Defense in Depth.",
        },
      },
    },
    {
      stepIndex: 1,
      type: "function_call",
      location: {
        folderId: "folder-middleware",
        folderName: "Middleware",
        fileId: "security-filter-cs",
        fileName: "SecurityFilter.cs",
        lineStart: 18,
        lineEnd: 25,
        symbol: "SecurityFilter.InspectPayload()",
        codeSnippet: "public bool InspectPayload(string raw) {\n    if (Regex.IsMatch(raw, @\"OR\\s+'1'='1'\")) {\n        throw new SecurityBreachException(\"SQL Injection detected\");\n    }\n    return true;\n}",
      },
      targetLocation: {
        folderId: "folder-middleware",
        folderName: "Middleware",
        fileId: "security-filter-cs",
        fileName: "SecurityFilter.cs",
        lineStart: 18,
        lineEnd: 25,
        symbol: "SecurityFilter.InspectPayload()",
      },
      callStackDepth: 2,
      callStack: ["NetworkListener.OnPacketReceived()", "SecurityFilter.InspectPayload()"],
      scopeVariables: {
        "patternMatch": true,
        "threatLevel": "CRITICAL",
      },
      explanation: {
        ua: "Система виявила сигнатуру тавтології '1'='1' і формує аварійне переривання.",
        en: "Heuristic detected tautology attack pattern and triggered security fault.",
        da: "Systemet opdagede angrebsmønster.",
      },
    },
    {
      stepIndex: 2,
      type: "exception",
      location: {
        folderId: "folder-middleware",
        folderName: "Middleware",
        fileId: "security-filter-cs",
        fileName: "SecurityFilter.cs",
        lineStart: 20,
        lineEnd: 20,
        symbol: "throw new SecurityBreachException()",
        codeSnippet: "throw new SecurityBreachException(\"SQL Injection detected\");",
      },
      targetLocation: {
        folderId: "root",
        folderName: "CyberBandit.Solution",
        fileId: "program-cs",
        fileName: "Program.cs",
        lineStart: 22,
        lineEnd: 22,
        symbol: "catch (SecurityBreachException ex)",
      },
      callStackDepth: 2,
      callStack: ["NetworkListener.OnPacketReceived()", "SecurityFilter.InspectPayload()"],
      returnValue: {
        type: "Exception",
        value: "SecurityBreachException",
        summary: {
          ua: "Атаку заблоковано фаєрволом!",
          en: "Attack blocked by firewall!",
          da: "Angreb blokeret!",
        },
        terminationReason: {
          ua: "Виконання методу аварійно перервано викликом throw Exception. Стек розгортається до найближчого блоку catch.",
          en: "Execution aborted via throw. Stack unwinds to enclosing try-catch block.",
          da: "Eksekvering afbrudt via throw Exception.",
        },
      },
      explanation: {
        ua: "Викинуто виняток SecurityBreachException! Стек екстрено скидається без виконання коду бази даних.",
        en: "SecurityBreachException thrown! Stack immediately unwinds without querying DB.",
        da: "SecurityBreachException udløst!",
      },
    },
    {
      stepIndex: 3,
      type: "return_unwind",
      location: {
        folderId: "root",
        folderName: "CyberBandit.Solution",
        fileId: "program-cs",
        fileName: "Program.cs",
        lineStart: 22,
        lineEnd: 24,
        symbol: "catch (SecurityBreachException ex)",
        codeSnippet: "catch (SecurityBreachException ex) {\n    Console.WriteLine($\"[DEFENSE ACTIVE] Dropped packet: {ex.Message}\");\n}",
      },
      callStackDepth: 1,
      callStack: ["NetworkListener.OnPacketReceived()"],
      explanation: {
        ua: "Блок catch перехопив загрозу. Пакет скинуто, інцидент зафіксовано в SIEM журналі.",
        en: "Catch block intercepted threat. Packet dropped, logged to SIEM.",
        da: "Catch-blok opfangede truslen.",
      },
    },
    {
      stepIndex: 4,
      type: "file_focus",
      location: {
        folderId: "root",
        folderName: "CyberBandit.Solution",
        fileId: "program-cs",
        fileName: "Program.cs",
        lineStart: 24,
        lineEnd: 26,
        symbol: "System [Safe]",
        codeSnippet: "// Invariant maintained: Database zero-leakage guarantee.",
      },
      callStackDepth: 1,
      callStack: ["NetworkListener.OnPacketReceived()"],
      explanation: {
        ua: "Периметр цілий. База даних не отримала шкідливого запиту.",
        en: "Perimeter secure. Database remained uncompromised.",
        da: "Databasen forblev sikker.",
      },
    },
  ],
};

export const VERTEX_EXECUTION_TRACE: ExecutionTraceTimeline = {
  id: "trace-vertex-cloud-mlops",
  stationId: "vertex",
  title: {
    ua: "Google Vertex AI MLOps: Pipeline -> GCS Lake -> Distributed GPU",
    en: "Google Vertex AI MLOps: Pipeline -> GCS Lake -> Distributed GPU",
    da: "Google Vertex AI MLOps: Pipeline -> GCS Lake -> Distributed GPU",
  },
  description: {
    ua: "Трасировка запуску навчального конвеєра: виділення ресурсів у VPC, завантаження батчів з GCS та публікація у Vertex Model Registry.",
    en: "Trace of distributed training pipeline: VPC provisioning, GCS batch ingestion, and publication to Vertex Model Registry.",
    da: "Sporing af distribueret træningspipeline i Vertex AI.",
  },
  language: "python",
  totalSteps: 4,
  steps: [
    {
      stepIndex: 0,
      type: "folder_enter",
      location: {
        folderId: "root",
        folderName: "VertexMLSolution",
        fileId: "program-cs",
        fileName: "pipeline.py",
        lineStart: 12,
        lineEnd: 16,
        symbol: "run_training_job()",
        codeSnippet: "job = aiplatform.CustomTrainingJob(\n    display_name='fraud-detector-v3',\n    script_path='pipeline.py'\n)\njob.run(dataset=gcs_dataset)",
      },
      callStackDepth: 1,
      callStack: ["run_training_job()"],
      scopeVariables: {
        dataset: "gcs://ml-lake/fraud-v3.parquet",
        accelerator: "NVIDIA_TESLA_A100",
      },
      explanation: {
        ua: "Оркестратор Kubeflow ініціює завдання розподіленого навчання у приватному VPC кластері Google Cloud.",
        en: "Kubeflow orchestrator triggers distributed training job within Google Cloud private VPC cluster.",
        da: "Kubeflow orchestrator starter distribueret træningsopgave i Google Cloud VPC.",
      },
      poeQuestion: {
        id: "poe-vertex-01",
        prompt: {
          ua: "Де зберігаються навчальні батчі даних перед початком епох на GPU?",
          en: "Where are training data batches stored before epochs commence on GPU?",
          da: "Hvor opbevares træningsdata før træning starter på GPU?",
        },
        options: [
          {
            id: "opt-gcs",
            targetFileId: "pipeline-spec",
            targetFolderId: "root",
            label: {
              ua: "В об'єктному сховищі GCS (Cloud Storage Lake)",
              en: "In GCS Object Storage (Cloud Storage Lake)",
              da: "I GCS objektlager (Cloud Storage Lake)",
            },
            isCorrect: true,
            feedback: {
              ua: "Точно! Хмарний конвеєр завантажує дані потоково з GCS, мінімізуючи накладні витрати пам'яті контейнера.",
              en: "Correct! Cloud pipeline streams training shards from GCS to eliminate local container memory bottlenecks.",
              da: "Korrekt! Cloud pipelinen streamer træningsdata fra GCS.",
            },
          },
          {
            id: "opt-local",
            targetFileId: "requirements-txt",
            targetFolderId: "root",
            label: {
              ua: "Локально всередині контейнера на SSD",
              en: "Locally inside the container SSD scratchpad",
              da: "Lokalt i containerens SSD",
            },
            isCorrect: false,
            feedback: {
              ua: "Ні. Терабайтні датасети не поміщаються у диск вузла, MLOps використовує розподілені бакети GCS.",
              en: "Incorrect. Terabyte datasets exceed local disk quotas; MLOps relies on remote GCS object storage.",
              da: "Forkert. Store datasæt opbevares i GCS buckets.",
            },
          },
        ],
        pedagogicalRationale: {
          ua: "Розуміння архітектури Big Data / Cloud MLOps: розмежування обчислень (GPU) та даних (GCS).",
          en: "Understanding cloud decoupling: separation of compute (GPU) and storage (GCS).",
          da: "Forståelse af afkobling mellem beregning og lagring.",
        },
      },
    },
    {
      stepIndex: 1,
      type: "file_focus",
      location: {
        folderId: "root",
        folderName: "VertexMLSolution",
        fileId: "pipeline-spec",
        fileName: "pipeline_spec.yaml",
        lineStart: 5,
        lineEnd: 9,
        symbol: "PipelineSpec.ProvisionAccelerators()",
        codeSnippet: "accelerator_type: ACCELERATOR_TYPE_A100\naccelerator_count: 8\nreplica_count: 4",
      },
      callStackDepth: 2,
      callStack: ["run_training_job()", "ProvisionAccelerators()"],
      scopeVariables: {
        totalGpus: 32,
        status: "RUNNING",
      },
      explanation: {
        ua: "Провайдер інфраструктури підключає 32 тензорні прискорювачі та виконує матричні обчислення зворотного поширення помилки.",
        en: "Infrastructure provider provisions 32 tensor accelerators executing distributed backpropagation matrix operations.",
        da: "Infrastrukturudbyderen tildeler 32 tensor-acceleratorer.",
      },
    },
    {
      stepIndex: 2,
      type: "function_call",
      location: {
        folderId: "root",
        folderName: "VertexMLSolution",
        fileId: "program-cs",
        fileName: "pipeline.py",
        lineStart: 28,
        lineEnd: 32,
        symbol: "deploy_to_endpoint()",
        codeSnippet: "endpoint = model.deploy(\n    machine_type='n1-standard-4',\n    min_replica_count=1,\n    max_replica_count=10\n)",
      },
      callStackDepth: 2,
      callStack: ["run_training_job()", "deploy_to_endpoint()"],
      scopeVariables: {
        endpointId: "ep-9941-vertex",
        trafficSplit: "100%",
      },
      explanation: {
        ua: "Модель успішно навчена: артефакт вагових коефіцієнтів деплоїться на REST інференс ендпоінт з автоскейлінгом.",
        en: "Model converged: weights artifact is deployed to auto-scaling REST inference endpoint.",
        da: "Modellen er trænet: vægte udrulles til REST inferens endepunkt.",
      },
    },
    {
      stepIndex: 3,
      type: "return_unwind",
      location: {
        folderId: "root",
        folderName: "VertexMLSolution",
        fileId: "program-cs",
        fileName: "pipeline.py",
        lineStart: 35,
        lineEnd: 36,
        symbol: "pipeline.completed()",
        codeSnippet: "return endpoint.resource_name",
      },
      targetLocation: {
        folderId: "root",
        folderName: "VertexMLSolution",
        fileId: "program-cs",
        fileName: "pipeline.py",
        lineStart: 12,
        lineEnd: 12,
        symbol: "run_training_job()",
      },
      callStackDepth: 1,
      callStack: ["run_training_job()"],
      returnValue: {
        type: "ModelEndpoint",
        value: "projects/941/locations/europe-west1/endpoints/7732",
        summary: {
          ua: "Конвеєр успішно завершив повний цикл: Ingestion -> Training -> Deployment.",
          en: "Pipeline successfully completed full lifecycle: Ingestion -> Training -> Deployment.",
          da: "Pipelinen har gennemført hele sin livscyklus.",
        },
        terminationReason: {
          ua: "Модель пройшла поріг F1-Score > 0.94 та розгорнута для обслуговування бойового трафіку.",
          en: "Model surpassed F1-Score threshold (>0.94) and was promoted to live inference serving.",
          da: "Modellen opfyldte kvalitetskriterierne.",
        },
      },
      explanation: {
        ua: "MLOps цикл завершено. Ендпоінт повертає ресурси у пул та очікує звернень клієнтських API.",
        en: "MLOps cycle concluded. Endpoint scales dynamically to meet incoming real-time traffic.",
        da: "MLOps cyklus fuldført.",
      },
    },
  ],
};

export const FDE_EXECUTION_TRACE: ExecutionTraceTimeline = {
  id: "trace-fde-agent-workflow",
  stationId: "fde",
  title: {
    ua: "Enterprise AI Agent: LangGraph -> Zero-Trust JWT -> Tool Execution",
    en: "Enterprise AI Agent: LangGraph -> Zero-Trust JWT -> Tool Execution",
    da: "Enterprise AI Agent: LangGraph -> Zero-Trust JWT -> Tool Execution",
  },
  description: {
    ua: "Трасировка агентного графа: валідація прав доступу замовника, виклик legacy ERP коннектора та фіксація незмінного аудит-журналу.",
    en: "Trace of enterprise agent workflow: zero-trust claim validation, legacy ERP connector dispatch, and immutable audit persistence.",
    da: "Sporing af enterprise AI agent arbejdsgang.",
  },
  language: "typescript",
  totalSteps: 4,
  steps: [
    {
      stepIndex: 0,
      type: "folder_enter",
      location: {
        folderId: "root",
        folderName: "AppliedAISolution",
        fileId: "program-cs",
        fileName: "agent_graph.ts",
        lineStart: 18,
        lineEnd: 22,
        symbol: "AgentWorkflow.Invoke()",
        codeSnippet: "const result = await workflow.invoke({\n  userQuery: 'Export client ledger Q3',\n  authToken: sessionJwt\n});",
      },
      callStackDepth: 1,
      callStack: ["AgentWorkflow.Invoke()"],
      scopeVariables: {
        callerRole: "AuditOfficer",
        sessionState: "AUTHENTICATED",
      },
      explanation: {
        ua: "Агент отримує запит на експорт звітності. Першим кроком граф перевіряє криптографічний токен сесії.",
        en: "Agent receives report export request. The agent graph first verifies the session cryptographic token.",
        da: "Agenten modtager anmodning og verificerer sessionens kryptografiske token.",
      },
      poeQuestion: {
        id: "poe-fde-01",
        prompt: {
          ua: "Куди перейде управління перед викликом інструмента читання бази даних?",
          en: "Where will execution flow transfer prior to invoking the database reading tool?",
          da: "Hvor flytter eksekveringen hen før databaseværktøjet kaldes?",
        },
        options: [
          {
            id: "opt-guard",
            targetFileId: "runbook-md",
            targetFolderId: "root",
            label: {
              ua: "До Zero-Trust перевірки прав доступу та PII фільтра",
              en: "To Zero-Trust claim verification and PII guardrails",
              da: "Til Zero-Trust rettighedsvalidering og PII-filter",
            },
            isCorrect: true,
            feedback: {
              ua: "Абсолютно вірно! Принцип найменших привілеїв зобов'язує валідувати дозволи до доступу до корпоративних даних.",
              en: "Spot on! Principle of Least Privilege mandates validating claim scopes prior to corporate data access.",
              da: "Præcis! Mindste privilegium-princippet kræver validering før dataadgang.",
            },
          },
          {
            id: "opt-direct",
            targetFileId: "package-json",
            targetFolderId: "root",
            label: {
              ua: "Напряму відправить SQL-запит в базу даних",
              en: "Directly send raw SQL query to the database",
              da: "Sende rå SQL direkte til databasen",
            },
            isCorrect: false,
            feedback: {
              ua: "Небезпечно! Пряме звернення без Zero-Trust валідації створює загрозу несанкціонованого витоку даних (OWASP LLM01).",
              en: "Hazardous! Bypassing claim validation causes critical data leakage vulnerabilities (OWASP LLM01).",
              da: "Farligt! Omgåelse af rettighedsvalidering skaber sikkerhedsrisici.",
            },
          },
        ],
        pedagogicalRationale: {
          ua: "Закріплення парадигми Enterprise AI Security: Zero-Trust валідація дій перед викликом корпоративних API.",
          en: "Reinforcing Enterprise AI Security: Zero-Trust action guards before internal API invocation.",
          da: "Forstærkning af Zero-Trust sikkerhed i AI.",
        },
      },
    },
    {
      stepIndex: 1,
      type: "file_focus",
      location: {
        folderId: "root",
        folderName: "AppliedAISolution",
        fileId: "runbook-md",
        fileName: "SRE_RUNBOOK.md",
        lineStart: 12,
        lineEnd: 15,
        symbol: "ZeroTrustGuard.AssertScope('ledger:read')",
        codeSnippet: "if (!claims.has('ledger:read')) {\n  throw new SecurityUnauthorizedException();\n}",
      },
      callStackDepth: 2,
      callStack: ["AgentWorkflow.Invoke()", "ZeroTrustGuard.AssertScope()"],
      scopeVariables: {
        verifiedScope: "ledger:read",
        piiMasked: true,
      },
      explanation: {
        ua: "Перевірка прав доступу успішно пройдена: токен містить необхідний scope ledger:read.",
        en: "Claim assertion passed: token contains requisite ledger:read permission scope.",
        da: "Rettighedskontrol bestået.",
      },
    },
    {
      stepIndex: 2,
      type: "function_call",
      location: {
        folderId: "root",
        folderName: "AppliedAISolution",
        fileId: "program-cs",
        fileName: "agent_graph.ts",
        lineStart: 30,
        lineEnd: 34,
        symbol: "LegacyERPAdapter.QueryLedger()",
        codeSnippet: "const ledger = await erpClient.fetchQuarterSummary('Q3');\nreturn sanitizePii(ledger);",
      },
      callStackDepth: 2,
      callStack: ["AgentWorkflow.Invoke()", "LegacyERPAdapter.QueryLedger()"],
      scopeVariables: {
        recordsCount: 1420,
        anonymized: true,
      },
      explanation: {
        ua: "Виклик legacy ERP-адаптера повертає фінансовий зріз. Семантичний бар'єр маскує персональні дані (PII).",
        en: "Legacy ERP adapter retrieves records. Semantic guardrail sanitizes personally identifiable information.",
        da: "ERP-adapter henter data og maskerer personlige oplysninger.",
      },
    },
    {
      stepIndex: 3,
      type: "return_unwind",
      location: {
        folderId: "root",
        folderName: "AppliedAISolution",
        fileId: "program-cs",
        fileName: "agent_graph.ts",
        lineStart: 40,
        lineEnd: 41,
        symbol: "workflow.complete()",
        codeSnippet: "return { report: sanitizedData, auditHash: hash };",
      },
      targetLocation: {
        folderId: "root",
        folderName: "AppliedAISolution",
        fileId: "program-cs",
        fileName: "agent_graph.ts",
        lineStart: 18,
        lineEnd: 18,
        symbol: "AgentWorkflow.Invoke()",
      },
      callStackDepth: 1,
      callStack: ["AgentWorkflow.Invoke()"],
      returnValue: {
        type: "AgentExecutionOutput",
        value: "{ status: 200, auditSha: 'f3a9...bc01' }",
        summary: {
          ua: "Агентний конвеєр завершив обробку із записом у криптографічний аудит-журнал.",
          en: "Agent pipeline concluded workflow with cryptographic audit log entry.",
          da: "Agentens arbejdsgang afsluttedes med krypteret revisionslog.",
        },
        terminationReason: {
          ua: "Запит успішно оброблено згідно з політиками безпеки SOC2 та HIPAA.",
          en: "Request fulfilled in full compliance with SOC2 and HIPAA security policies.",
          da: "Anmodning opfyldt i overensstemmelse med sikkerhedspolitikker.",
        },
      },
      explanation: {
        ua: "Результат повернено клієнту. Всі дії верифіковані та зафіксовані в незмінному реєстрі подій.",
        en: "Verified payload returned to client. Actions permanently audited in immutable ledger.",
        da: "Verificeret resultat returneret til klient.",
      },
    },
  ],
};

// ── Station 09: IBM RAG & Agentic AI Architecture Trace ───────────────────────
export const RAG_EXECUTION_TRACE: ExecutionTraceTimeline = {
  id: "trace-rag-neural-pipeline",
  stationId: "rag",
  title: {
    ua: "Конвеєр нейронного пошуку: Chunker -> VectorStore -> RRF -> ReAct Loop",
    en: "Neural Retrieval Pipeline: Chunker -> VectorStore -> RRF -> ReAct Loop",
    da: "Neural Søgepipeline: Chunker -> VectorStore -> RRF -> ReAct Loop",
  },
  description: {
    ua: "Покрокова трасировка проходження запиту через рекурсивний чанкінг, розрахунок косинусної схожості та цикл ReAct міркувань.",
    en: "Step-by-step trace of query execution through recursive chunking, cosine distance computation, and the ReAct reasoning loop.",
    da: "Trin-for-trin sporing af forespørgsel gennem rekursiv chunking, cosinus-beregning og ReAct ræsonnementsløkke.",
  },
  language: "python",
  totalSteps: 5,
  steps: [
    {
      stepIndex: 0,
      type: "folder_enter",
      location: {
        folderId: "root",
        folderName: "ibm-rag-agentic-suite",
        fileId: "rag-chunker",
        fileName: "document_chunker.py",
        lineStart: 12,
        lineEnd: 24,
        symbol: "chunk_document()",
        codeSnippet: "def chunk_document(text: str, chunk_size: int = 256, overlap: int = 40) -> list[str]:\n    step = max(1, chunk_size - overlap)\n    chunks = [text[i:i+chunk_size] for i in range(0, len(text), step)]\n    return chunks",
      },
      callStackDepth: 1,
      callStack: ["chunk_document()"],
      scopeVariables: {
        chunk_size: "256 chars",
        overlap: "40 chars",
        step: "216 chars",
      },
      explanation: {
        ua: "Текстовий документ нарізається на фрагменти фіксованого розміру з ковзним вікном перекриття для збереження контексту.",
        en: "Document text is partitioned into bounded fragments with a sliding overlap window to preserve semantic boundary context.",
        da: "Dokumentteksten opdeles i bidder med et glidende overlap for at bevare semantisk kontekst.",
      },
      poeQuestion: {
        id: "poe-rag-01",
        prompt: {
          ua: "Чому перекриття (overlap) критично важливе при розбитті документів для RAG?",
          en: "Why is chunk overlap critical when partitioning documents for RAG systems?",
          da: "Hvorfor er chunk-overlap afgørende ved opdeling af dokumenter til RAG?",
        },
        options: [
          {
            id: "opt-context",
            targetFileId: "rag-chunker",
            targetFolderId: "root",
            label: {
              ua: "Запобігає розриву семантичного контексту важливих речень на стику блоків",
              en: "Prevents semantic context loss across boundary sentences between adjacent chunks",
              da: "Forhindrer tab af semantisk kontekst ved sætningsgrænser mellem bidder",
            },
            isCorrect: true,
            feedback: {
              ua: "Абсолютно вірно! Без перекриття речення, розрізане посередині, втрачає сенс при векторному пошуку.",
              en: "Spot on! Sentences bisected at boundaries without overlap lose their contextual vector representation.",
              da: "Korrekt! Uden overlap mister sætninger på kanten deres betydning.",
            },
          },
          {
            id: "opt-compression",
            targetFileId: "rag-chunker",
            targetFolderId: "root",
            label: {
              ua: "Стискає розмір бази даних у два рази",
              en: "Compresses vector database footprint by 50%",
              da: "Komprimerer databasestørrelsen med 50%",
            },
            isCorrect: false,
            feedback: {
              ua: "Хибно! Перекриття навпаки трохи збільшує загальну кількість токенів, але захищає якість пошуку.",
              en: "Incorrect! Overlap slightly increases total indexed tokens, but strictly safeguards retrieval quality.",
              da: "Forkert! Overlap øger mængden af tokens en smule for at sikre kvaliteten.",
            },
          },
        ],
        pedagogicalRationale: {
          ua: "Розуміння дилеми чанкінгу: баланс між гранулярністю блоків та збереженням смислового контексту.",
          en: "Grasping the chunking trade-off: balancing fragment granularity against semantic context retention.",
          da: "Forståelse af afvejningen mellem fragmentstørrelse og kontekstbevarelse.",
        },
      },
    },
    {
      stepIndex: 1,
      type: "file_focus",
      location: {
        folderId: "root",
        folderName: "ibm-rag-agentic-suite",
        fileId: "rag-vectorstore",
        fileName: "vector_store.py",
        lineStart: 35,
        lineEnd: 48,
        symbol: "VectorStore.l2_normalize()",
        codeSnippet: "def l2_normalize(vector: list[float]) -> list[float]:\n    norm = math.sqrt(sum(x ** 2 for x in vector))\n    return [x / norm for x in vector] if norm > 0 else vector",
      },
      callStackDepth: 2,
      callStack: ["chunk_document()", "VectorStore.l2_normalize()"],
      scopeVariables: {
        dimensions: "R^8 coordinate space",
        l2_norm: "1.000 (Unit Sphere)",
      },
      explanation: {
        ua: "Векторні ембеддінги нормалізуються до одиничної довжини. Це дозволяє розраховувати косинусний зв'язок через швидкий скалярний добуток.",
        en: "Vector embeddings are normalized to unit length, enabling fast cosine similarity ranking via hardware SIMD dot product.",
        da: "Vektorer normaliseres til enhedslængde for lynhurtig skalarprodukt-beregning.",
      },
    },
    {
      stepIndex: 2,
      type: "function_call",
      location: {
        folderId: "root",
        folderName: "ibm-rag-agentic-suite",
        fileId: "rag-vectorstore",
        fileName: "vector_store.py",
        lineStart: 60,
        lineEnd: 74,
        symbol: "reciprocal_rank_fusion()",
        codeSnippet: "def reciprocal_rank_fusion(dense_ranks, sparse_ranks, k=60):\n    scores = {}\n    for doc_id, rank in dense_ranks.items():\n        scores[doc_id] = scores.get(doc_id, 0.0) + 1.0 / (k + rank)\n    return sorted(scores.items(), key=lambda x: x[1], reverse=True)",
      },
      callStackDepth: 2,
      callStack: ["chunk_document()", "reciprocal_rank_fusion()"],
      scopeVariables: {
        rrf_constant_k: "60",
        top_k: "3 documents",
      },
      explanation: {
        ua: "Алгоритм RRF об'єднує результати семантичного векторного пошуку та пошуку за ключовими словами без необхідності ручного налаштування ваг.",
        en: "RRF merges dense neural rankings and sparse keyword hits, neutralizing score disparities without manual weight tuning.",
        da: "RRF-algoritmen forener tæt og spredt søgning for optimal præcision.",
      },
    },
    {
      stepIndex: 3,
      type: "function_call",
      location: {
        folderId: "root",
        folderName: "ibm-rag-agentic-suite",
        fileId: "rag-react-agent",
        fileName: "react_agent.py",
        lineStart: 45,
        lineEnd: 58,
        symbol: "ReActAgent.step()",
        codeSnippet: "def step(self, state: AgentState) -> AgentAction:\n    thought = self.reason(state.query, state.retrieved_context)\n    action = self.decide_tool(thought)\n    return AgentAction(thought=thought, action=action)",
      },
      callStackDepth: 2,
      callStack: ["chunk_document()", "ReActAgent.step()"],
      scopeVariables: {
        loop_stage: "THOUGHT -> ACTION",
        agent_role: "IBM ReAct Reasoning Agent",
      },
      explanation: {
        ua: "Агент аналізує витягнуті документи, формулює гіпотезу міркування (Thought) та обирає виклик інструменту (Action).",
        en: "Agent inspects retrieved facts, forms diagnostic hypothesis (Thought), and selects appropriate deterministic tool execution (Action).",
        da: "Agenten analyserer kilderne, danner en hypotese og vælger værktøj.",
      },
    },
    {
      stepIndex: 4,
      type: "return_unwind",
      location: {
        folderId: "root",
        folderName: "ibm-rag-agentic-suite",
        fileId: "rag-react-agent",
        fileName: "react_agent.py",
        lineStart: 85,
        lineEnd: 92,
        symbol: "ReActAgent.finalize_response()",
      },
      callStackDepth: 1,
      callStack: ["ReActAgent.finalize_response()"],
      returnValue: {
        type: "GroundedAgentResponse",
        value: "{ status: 'GROUNDED', faithfulness: 0.98, answer: 'Verified SLA...' }",
        summary: {
          ua: "Агент сформував верифіковану відповідь із цитуванням джерел знань.",
          en: "Agent returned verified response grounded 100% in retrieved knowledge chunks.",
          da: "Agenten returnerede verificeret svar med kildehenvisninger.",
        },
        terminationReason: {
          ua: "Оцінка RAGAS Faithfulness склала 0.98, ризик галюцинацій усунуто.",
          en: "RAGAS Faithfulness reached 0.98, generative hallucinations fully mitigated.",
          da: "RAGAS pålidelighed nåede 0.98 uden hallucinationer.",
        },
      },
      explanation: {
        ua: "Конвеєр RAG успішно завершив роботу: користувач отримав достовірну відповідь з точними посиланнями на документи.",
        en: "RAG pipeline successfully fulfilled query: verified answer returned with exact document references.",
        da: "RAG-pipelinen fuldførte opgaven med verificerede kildehenvisninger.",
      },
    },
  ],
};

// ── Station 10: Google Cybersecurity & SOC Defense Trace ───────────────────────
export const CYBER_EXECUTION_TRACE: ExecutionTraceTimeline = {
  id: "trace-cyber-soc-containment",
  stationId: "cyber",
  title: {
    ua: "Ланцюг захисту периметра: Syslog Ingestion -> Wireshark -> Chronicle SIEM -> iptables DROP",
    en: "Perimeter Defense Chain: Syslog Ingestion -> Wireshark -> Chronicle SIEM -> iptables DROP",
    da: "Forsvarskæde: Syslog Ingestion -> Wireshark -> Chronicle SIEM -> iptables DROP",
  },
  description: {
    ua: "Покрокова трасировка виявлення мережевої аномалії, дисекції пакетів у Wireshark, мапування на MITRE ATT&CK та ізоляції вузла за стандартом NIST CSF.",
    en: "Step-by-step trace of network anomaly detection, Wireshark packet dissection, MITRE ATT&CK mapping, and host isolation via NIST CSF.",
    da: "Trin-for-trin sporing af netværksanomali, Wireshark pakkeanalyse, MITRE ATT&CK kortlægning og NIST CSF hændelsesrespons.",
  },
  language: "python",
  totalSteps: 5,
  steps: [
    {
      stepIndex: 0,
      type: "folder_enter",
      location: {
        folderId: "root",
        folderName: "google-cybersecurity-soc",
        fileId: "cyber-syslog",
        fileName: "syslog_parser.py",
        lineStart: 15,
        lineEnd: 28,
        symbol: "parse_syslog_line()",
        codeSnippet: "def parse_syslog_line(raw_line: str) -> dict:\n    ip_match = re.search(r'\\b(?:\\d{1,3}\\.){3}\\d{1,3}\\b', raw_line)\n    source_ip = ip_match.group(0) if ip_match else '127.0.0.1'\n    return {'source_ip': source_ip, 'severity': 'CRITICAL'}",
      },
      callStackDepth: 1,
      callStack: ["parse_syslog_line()"],
      scopeVariables: {
        raw_stream: "RFC 5424 Syslog line",
        extracted_ip: "192.168.1.105",
        severity: "CRITICAL",
      },
      explanation: {
        ua: "Сирий потік системних логів парситься регулярними виразами: витягується IP джерела та прапорець критичності події.",
        en: "Raw syslog text stream is ingested and parsed via regex, extracting source IP and security severity level.",
        da: "Rå syslog-tekst parses for at udtrække kilde-IP og hændelsens alvorsgrad.",
      },
      poeQuestion: {
        id: "poe-cyber-01",
        prompt: {
          ua: "Чому нормалізація Syslog-логів є обов'язковим першим кроком у роботі SOC?",
          en: "Why is Syslog normalization a mandatory prerequisite in SOC operations?",
          da: "Hvorfor er Syslog-normalisering et obligatorisk første skridt i en SOC?",
        },
        options: [
          {
            id: "opt-correlation",
            targetFileId: "cyber-syslog",
            targetFolderId: "root",
            label: {
              ua: "Зводить різнорідні формати до єдиної схеми для швидкої кореляції алертерів у SIEM",
              en: "Normalizes disparate log schemas into uniform events for cross-system SIEM correlation",
              da: "Standardiserer forskellige logformater til SIEM-korrelation",
            },
            isCorrect: true,
            feedback: {
              ua: "Абсолютно вірно! Без нормалізації неможливо зіставити логи фаєрвола, веб-сервера та бази даних.",
              en: "Correct! Cross-source correlation is impossible without mapping raw text to unified schema.",
              da: "Præcis! Ensartede data er nødvendige for at sammenkoble hændelser.",
            },
          },
          {
            id: "opt-crypto",
            targetFileId: "cyber-syslog",
            targetFolderId: "root",
            label: {
              ua: "Шифрує жорсткий диск сервера",
              en: "Encrypts the host operating system disk",
              da: "Krypterer serverens harddisk",
            },
            isCorrect: false,
            feedback: {
              ua: "Хибно! Парсинг займається структуруванням тексту, а не шифруванням файлової системи.",
              en: "Incorrect! Syslog parsing extracts metadata, it does not encrypt disk volumes.",
              da: "Forkert! Parsing analyserer data, det krypterer ikke disken.",
            },
          },
        ],
        pedagogicalRationale: {
          ua: "Формування розуміння архітектури SIEM: від сирих джерел до єдиного аналітичного озера подій.",
          en: "Understanding SIEM architecture: from raw edge log streams to unified analytics data lakes.",
          da: "Forståelse af SIEM-dataindsamling og analyse.",
        },
      },
    },
    {
      stepIndex: 1,
      type: "file_focus",
      location: {
        folderId: "root",
        folderName: "google-cybersecurity-soc",
        fileId: "cyber-wireshark",
        fileName: "packet_dissector.py",
        lineStart: 30,
        lineEnd: 46,
        symbol: "dissect_pcap_frame()",
        codeSnippet: "def dissect_pcap_frame(raw_bytes: bytes) -> DissectedFrame:\n    eth = parse_ethernet(raw_bytes[:14])\n    ip = parse_ipv4(raw_bytes[14:34])\n    tcp = parse_tcp(raw_bytes[34:54])\n    return DissectedFrame(eth, ip, tcp)",
      },
      callStackDepth: 2,
      callStack: ["parse_syslog_line()", "dissect_pcap_frame()"],
      scopeVariables: {
        ethernet_src: "00:1a:2b:3c:4d:5e",
        ip_flags: "DF (Don't Fragment)",
        tcp_flags: "SYN (0x002) - Port 80",
      },
      explanation: {
        ua: "Web-Wireshark розбирає сирі байти кадру: аналізуються MAC-адреси, IP-заголовки та бітові прапорці TCP SYN.",
        en: "Web-Wireshark dissects raw PCAP frames: verifying MAC addresses, IPv4 headers, and TCP SYN control flags.",
        da: "Web-Wireshark analyserer rå netværksrammer og verificerer TCP SYN flag.",
      },
    },
    {
      stepIndex: 2,
      type: "function_call",
      location: {
        folderId: "root",
        folderName: "google-cybersecurity-soc",
        fileId: "cyber-chronicle",
        fileName: "chronicle_engine.py",
        lineStart: 42,
        lineEnd: 55,
        symbol: "ChronicleEngine.evaluate_mitre()",
        codeSnippet: "def evaluate_mitre(event: SecurityEvent) -> MitreTTP:\n    if event.syn_ratio > 10.0:\n        return MitreTTP(id='T1499', name='Endpoint Denial of Service')\n    return MitreTTP(id='T1110', name='Brute Force')",
      },
      callStackDepth: 2,
      callStack: ["parse_syslog_line()", "ChronicleEngine.evaluate_mitre()"],
      scopeVariables: {
        mitre_tactic: "T1499 (Denial of Service)",
        chronicle_query: "eventCategory = 'auth' AND severity = 'CRITICAL'",
      },
      explanation: {
        ua: "Движок Chronicle зіставляє аномалію з матрицею MITRE ATT&CK: зафіксовано техніку T1499 (Denial of Service).",
        en: "Chronicle rule engine maps anomaly to MITRE ATT&CK: adversary TTP identified as T1499 (Denial of Service).",
        da: "Chronicle forbinder anomalien til MITRE ATT&CK T1499 taktikken.",
      },
    },
    {
      stepIndex: 3,
      type: "function_call",
      location: {
        folderId: "root",
        folderName: "google-cybersecurity-soc",
        fileId: "cyber-nist",
        fileName: "nist_containment.py",
        lineStart: 25,
        lineEnd: 38,
        symbol: "NistContainmentMachine.advance_stage()",
        codeSnippet: "def advance_stage(incident_id: str) -> NistStage:\n    stage = NistStage.CONTAINMENT\n    audit_log.append(f'Incident {incident_id} escalated to {stage}')\n    return stage",
      },
      callStackDepth: 2,
      callStack: ["parse_syslog_line()", "NistContainmentMachine.advance_stage()"],
      scopeVariables: {
        nist_framework: "NIST CSF 2.0",
        current_phase: "CONTAINMENT (Stage 2/5)",
      },
      explanation: {
        ua: "SOC-аналітик активує протокол NIST CSF 2.0: інцидент переведено на стадію негайної локалізації (Containment).",
        en: "SOC analyst executes NIST CSF 2.0 protocol: incident escalated to active host containment stage.",
        da: "SOC-analytikeren aktiverer NIST CSF 2.0 indæmningsprotokol.",
      },
    },
    {
      stepIndex: 4,
      type: "return_unwind",
      location: {
        folderId: "root",
        folderName: "google-cybersecurity-soc",
        fileId: "cyber-firewall",
        fileName: "firewall_manager.py",
        lineStart: 50,
        lineEnd: 58,
        symbol: "apply_iptables_drop()",
      },
      callStackDepth: 1,
      callStack: ["apply_iptables_drop()"],
      returnValue: {
        type: "FirewallEnforcementResult",
        value: "iptables -A INPUT -s 192.168.1.105 -j DROP (STATUS: 200 ENFORCED)",
        summary: {
          ua: "Правило Netfilter застосовано в ядрі: шкідливу IP-адресу заблоковано.",
          en: "Netfilter firewall rule committed to kernel: adversary IP dropped unconditionally.",
          da: "Netfilter firewall-regel aktiveret i kernen: angriberens IP blokeret.",
        },
        terminationReason: {
          ua: "Загрозу нейтралізовано, периметр корпоративної мережі відновлено.",
          en: "Threat permanently neutralized, enterprise perimeter integrity restored.",
          da: "Truslen er neutraliseret og netværkssikkerheden genoprettet.",
        },
      },
      explanation: {
        ua: "Фінал реагування: команда iptables скидає всі вхідні пакети атакуючого вузла на рівні ядра Linux.",
        en: "Response complete: iptables rule drops all inbound traffic from attacker IP at Linux kernel boundary.",
        da: "Afslutning: iptables blokerer al trafik fra angriberens IP i kernen.",
      },
    },
  ],
};

export const STATION_TRACES: Record<string, ExecutionTraceTimeline> = {
  tv: SMART_TV_EXECUTION_TRACE,
  api: API_FORGE_EXECUTION_TRACE,
  pos: POS_EXECUTION_TRACE,
  git: GIT_EXECUTION_TRACE,
  bandit: BANDIT_EXECUTION_TRACE,
  vertex: VERTEX_EXECUTION_TRACE,
  fde: FDE_EXECUTION_TRACE,
  rag: RAG_EXECUTION_TRACE,
  cyber: CYBER_EXECUTION_TRACE,
};

export function getStationTrace(stationId: string): ExecutionTraceTimeline {
  return STATION_TRACES[stationId] || SMART_TV_EXECUTION_TRACE;
}


